version: "3.10"

services:
  backend:
    build: .
    container_name: yamanashi-event-notify-backend
    env_file:
      - .env
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - .:/app
    restart: unless-stopped